### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by WhoisBsa** [WhoisBsa/amporal#1]
**Primeiros Passos:**
- [x] Escolha do Framework
- [x] Aprender como usá-lo
- [x] Escolher Banco de Dados
- [x] Criar repositório
- [x] Adicionar ToDo List

**Layout:**
- [x] Escolha da ferramenta
- [x] Criar o logo
- [x] Criar design das telas de:
    - [x] Preload
    - [x] Login
    - [x] Sign in
    - [x] Home
    - [x] HomeConfig
    - [x] Profile
    - [x] Aulas
    - [x] Questionário

**PROJETO:**
- [x] Iniciar projeto do zero
- [x] Adicionar `redux` e `redux-persist`
- [x] Adicionar `Assync Storage`
- [x] Adicionar `react-navigation` (`tabs` e `stack`)
- [x] Telas:
    - [x] Preload
    - [x] Login
    - [x] Sign in
    - [x] Home
    - [x] HomeConfig
    - [x] Profile
    - [x] Aulas
    - [x] Questionário
- [x] Adicionar vídeo-aulas
- [x] Adicionar perguntas ao questionário
- [x] Finalizar o projeto
